### ISSUE TITLE
click handler fires too early

### ISSUE THREAD

**Issue by bardware** [jmschabdach/bootstrap-tabdrop#13]
Hi,

you handle the click in a dropdown with a handler you setup like so: `this.element.on('click', 'li:not(.tabdrop)', boundLayout);`
This fires before the standard bootstrap handler 
```
 $(document)
    .on('click.bs.tab.data-api', '[data-toggle="tab"]', clickHandler)
    .on('click.bs.tab.data-api', '[data-toggle="pill"]', clickHandler)
``` 
fires.

Your plugin reads the inner html of the selected option to display in the single tab all tabs are collapsed to. Since the class `.active' has not been set to the newly selected item, the title of the previously selected tab is written to the tabdrop. It's always one click behind for me.

**Comment by rkenney** [comment]
I know this is a few months old but i ran into the same issue, to fix this i i modified the TabDrop function like so.
```javascript
 WinResizer.register(boundLayout);
//i removed the line below 
//this.element.on('click', 'li:not(.tabdrop)', boundLayout);
//and added the following to watch for the bootstrap event to finish.
 this.element.on('shown.bs.tab', function (e) {
     boundLayout();
 });

this.teardown = function () {
    WinResizer.unregister(boundLayout);
     //this.element.off('click', 'li:not(.tabdrop)', boundLayout);
     this.element.off('shown.bs.tab', function (e) {
         boundLayout();
    });
};

**Comment by frogabog** [comment]
I've applied the above changes, yet the issue persists.  I see no change from the original where the active tab shown is 1 click behind.

**Comment by rkenney** [comment]
@frogabog what version of bootstrap are you using?

**Comment by frogabog** [comment]
@rkenney, Bootstrap 3.3.5

**Comment by rkenney** [comment]
@frogabog i have a fork of this repo that i am using in a current project that i have modified to allow me to specify if and what bootstrap version i am using like so: 
```js
$('#nav-tab').tabdrop({ text: "<i class='fa fa-bars'></i>", usingBootstrap3: true });
```
you can get a copy of the fork here https://github.com/rkenney/bootstrap-tabdrop
and give it a try, let me know if you are successful

**Comment by frogabog** [comment]
Actually yes, it works nicely now.  However I think my mistake was leaving ('layout') in the call because it didn't work till I removed it. Thank you!

**Comment by rkenney** [comment]
Happy to help
